### ISSUE TITLE
✨ husky를 활용해 package-lock.json 변경시 npm ci를 동작할 수 있도록 post-merge script를 생성

### ISSUE THREAD

**Issue by rkskekzzz** [80000Coding/80000Coding-Web-Client#110]
## 추가할 기능
아이디어를 실천합니다..
<img width="677" alt="image" src="https://github.com/80000Coding/80000Coding-Web-Client/assets/57925497/61124730-037e-4bbb-affb-2cfcf90d1f27">

- [husky 설정 참고 링크](https://library.gabia.com/contents/8492/)
- [post-merge script 구현시 참고 링크](https://dev.to/zirkelc/automatically-install-npm-dependencies-on-git-pull-bg0)

## 할 일 목록
- [ ] husky 설정
- [ ] post-merge script 작성

**Comment by leekh716** [comment]
![image](https://github.com/80000Coding/80000Coding-Web-Client/assets/76505351/3b4bf621-7aab-4a94-ba4b-0b59cd9ad3a6)
요것까지 캡쳐해주신 깨알 수형님 ㅋㅋㅋㅋㅋㅋ
