### ISSUE TITLE
♻️ tailwind 커스텀 색상 추가 위치를 theme에서 theme.extend 로 변경

### ISSUE THREAD

**Issue by rkskekzzz** [80000Coding/80000Coding-Web-Client#146]
## 수정할 기능
tailwind 커스텀 색상을 theme 아래에 두었을 때, 기존에 정의된 색상도 사용하지 못하는 단점이 발생합니다.
```jsx
// transparent를 따로 정의하지 않으면 원래 정의된 색상이라도 사용이 불가능
<div className='bg-transparent' />
```
theme.extend 아래로 위치를 옮기면 transparent, white, black 등 기존에 정의된 색상을 다시 추가하지 않더라도 사용이 가능합니다. 

하지만 이렇게 사용할 경우, 서비스에서 사용하는 색상 이외에도 타입추론이 되어버려서 불편한 점이 생길 수 있습니다. 기존 정의된 색상은 많아도 5개 이내일 것 같아서 필요한 색상을 추가해서 사용해도 문제가 없어보이긴 합니다. 아래에 두가지 방법에 대한 공식 문서 링크를 남겨두었습니다. 의견 부탁드립니다!

https://tailwindcss.com/docs/customizing-colors#using-the-default-colors
https://tailwindcss.com/docs/customizing-colors#adding-additional-colors

**Comment by ash0814** [comment]
저는 회의때 말씀드린대로 theme.extend 아래로 색상 위치 옮기는 게 좋다고 생각합니다...! 그때 옮기고 prefix 추가하는 방법도 있지 않았나욤?

**Comment by leekh716** [comment]
저도 기존 색상 그대로 두는게 조을거같아여~~ extend 아래로 !!
