### ISSUE TITLE
✨Text 스타일 수정 및 적용 방식 변경

### ISSUE THREAD

**Issue by hanjiwon1** [80000Coding/80000Coding-Web-Client#92]
## 추가할 기능
✨Text 스타일 수정 및 적용 방식 변경

## 할 일 목록
- [x] 텍스트 스타일 디자인 시안에 맞게 수정
- [x] 텍스트 `컴포넌트` -> `@apply` 로 방식 변경
- [x] 기존 텍스트 컴포넌트 호출 영역 수정

## 설명
기존 임의로 분류하여 정의한 텍스트 스타일을 디자인 시스템에 맞게 수정합니다.
또한 텍스트 컴포넌트 사용 시 모든 텍스트가 div 태그로 감싸졌던 이슈 (?) 해결을 위해 tailwind에서 제공하는 `@apply` 방식을 사용하는 것으로 변경합니다.

**Comment by ash0814** [comment]
Finish!
